name: complete_todo_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_local_notifications: ^11.0.1
  flutter_native_timezone: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^1.1.5
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  intl: ^0.17.0
  rxdart: ^0.27.5
  sqflite: 2.0.3+1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.jpeg"
dev_dependencies:
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/person.jpeg
    - assets/images/task.svg
